### ISSUE TITLE
allow `{% attrs %}` to render hyphenated attributes ( `aria-label`, `data-script` etc)

### ISSUE THREAD

**Issue by lolrenx** [mixxorz/slippers#16]
from htmx.org
> htmx gives you access to [AJAX](https://htmx.org/docs#ajax), [CSS Transitions](https://htmx.org/docs#css_transitions), [WebSockets](https://htmx.org/docs#websockets) and [Server Sent Events](https://htmx.org/docs#sse) directly in HTML, using [attributes](https://htmx.org/reference#attributes), so you can build [modern user interfaces](https://htmx.org/examples) with the [simplicity](https://en.wikipedia.org/wiki/HATEOAS) and [power](https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm) of hypertext

htmx attributes are represented in templates tags like other attributes. 
potential caveat : they are defined with a hyphen `hx-get` , `hx-target`, `hx-swap` ... 

this enhancement could also increase compatibility with alpine, hyperscript and other frameworks that make use of custom HTML attributes, and attrs that are defined with hyphens such as `aria-label`

Happy to contribute to implementation

**Comment by mixxorz** [comment]
Hey. Thanks for bringing this to my attention. I hadn't considered attributes with hyphens.

I've opened a PR to address the issue. Do let me know if that works for you.

#17

**Comment by lolrenx** [comment]
Thanks for your qui response. tried a couple `aria-label` and htmx attributes, they render fine! 
this will drastically simplify my components, thanks a lot! Now I have to refactor my spaghetti code 👍

**Comment by mixxorz** [comment]
This has been released with 0.4.0

https://github.com/mixxorz/slippers/releases/tag/0.4.0

**Comment by lolrenx** [comment]
awesome, thank you !

**Comment by mixxorz** [comment]
I've released version `0.5.0a0` which makes this case "just work" without any workarounds.

```
pip install slippers==0.5.0a0
```
