### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by NgariC** [mixxorz/slippers#42]
Its not compatible with Django 4.2

**Comment by mschoettle** [comment]
It's been fixed with #32 but it's unfortunately not released yet.

/cc @mixxorz

**Comment by KeytonRR** [comment]
Any word on this release?

**Comment by RileyMathews** [comment]
Also curious about this? I want to try out slippers in a brand new Django project I'm spinning up using 4.2.2

**Comment by CleitonDeLima** [comment]
Waiting for the release of the new version.

**Comment by mschoettle** [comment]
@mixxorz

**Comment by mixxorz** [comment]
Sorry for the delay. 0.6.0 is now released.
