### ISSUE TITLE
Inline component defines nodelist as None

### ISSUE THREAD

**Issue by topher235** [mixxorz/slippers#48]
The nodelist being defined as `None` for inline components is causing some incompatibility issues with other libraries, e.g. [django-render-block](https://github.com/clokep/django-render-block), because they can't iterate over `None`. I think the value set should be an empty list or [NodeList](https://github.com/django/django/blob/main/django/template/base.py#L994).

https://github.com/mixxorz/slippers/blob/0ce084f11a33c01d3264a81e8ead3f06aedf4b2c/slippers/templatetags/slippers.py#L29

**Comment by mixxorz** [comment]
Fixed by #49
